{% set name = "click-help-colors" %}
{% set version = "0.6" %}
{% set sha256 = "258d5f4d79e54af8d017c07313456db22e636c964dd0808a2fb0aefc654ee30c" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - click

test:
  imports:
    - click_help_colors

about:
  home: https://github.com/r-m-n/click-help-colors
  license: MIT
  # License file missing on pypi. See: https://github.com/r-m-n/click-help-colors/issues/2
  #license_file: LICENSE.txt
  summary: 'Colorization of help messages in Click'
  dev_url: https://github.com/r-m-n/click-help-colors
  license_family: MIT

extra:
  recipe-maintainers:
    - saketkc
